### ISSUE TITLE
POLYLINE problem

### ISSUE THREAD

**Issue by MangakaFan** [cvdlab/plasm.js#10]
Sto provando ad utilizzare POLYLINE per dell'homework, ma ho un problema. Il codice che ho eseguito è il seguente:

var points = [[0,0], [1,1], [2,0], [3,1], [4,0]];
var polyline = POLYLINE(points);
DRAW(polyline);

Non mi da alcun errore, ma mi visualizza solo i primi due segmenti(da [0,0] a [1,1] e da [1,1] a [2,0]) tralasciando gli altri.
La sto usando male?

**Comment by federicospini** [comment]
puoi riprovare e darmi un feedback?

grazie :)

**Comment by MangakaFan** [comment]
Ora funziona perfettamente (ho provato sia con l'esempio di prima che con un'altro più grande).
Grazie!!!

**Comment by federicospini** [comment]
OK

buon lavoro :)
