### ISSUE TITLE
Visualizzatore in locale

### ISSUE THREAD

**Issue by pmartella** [cvdlab/plasm.js#14]
Ciao, volevo chiedervi la procedura per utilizzare il visualizzatore di plasm.js (reperibile all' indirizzo http://cvdlab.github.com/plasm.js/) in locale.
Mi sarebbe molto utile dato che, molto spesso, mi trovo a lavorare in condizioni di assenza di connessione ad Internet.
Vi ringrazio in anticipo per la risposta.

**Comment by vittorioc** [comment]
Mi permetto di risponderti.

Come è indicato sul sito 
https://github.com/cvdlab/plasm.js

se lavori in ambiente linux (io ho ubuntu) basta avere installati i seguenti programmi:

git
nodejs
npm

poi apri un terminale ed esegui questi comandi

git clone git@github.com:cvdlab/plasm.js.git
cd plasm.js
npm install 

il primo comando clona il repository in locale
il secondo comando ti sposta all'interno della directory appena creata
il terzo comando installa due "librerie" necessarie al funzionamento di plasm.js

ho avuto un solo problema seguendo questa procedura, alla fine l'ho risolto aggiornando il programma npm all'ultima versione, se vuoi controllare la versione di npm installata basta digitare

npm -v

con la versione 1.1.4 è tutto ok

**Comment by pmartella** [comment]
Ho seguito le istruzioni ma non sono ancora riuscito. 
Sarà perchè la mia versione di npm è la 1.1.16?
Comunque ho provato anche ad effettuare l' npm update, ma la versione resta la stessa..

**Comment by vittorioc** [comment]
Ho aggiornato npm alla versione 1.1.16 e ho riprovato tutta la procedura e funziona...

Sei sotto linux?

Quale risposta ricevi dal sistema digitando i comandi

git clone git@github.com:cvdlab/plasm.js.git

cd plasm.js

npm install

**Comment by pmartella** [comment]
No sono sotto Windows. Comunque la procedura sembra andare a buon fine; ecco cosa mi restituisce il terminale di GIT:
$ git clone git@github.com:cvdlab/plasm.js.git
Cloning into 'plasm.js'...
remote: Counting objects: 1303, done.
remote: Compressing objects: 100% (494/494), done.
remote: Total 1303 (delta 742), reused 1291 (delta 734)Receiving objects:  88% (
Receiving objects:  89% (1160/1303), 668.00 KiB | 251 KiB/s
Receiving objects: 100% (1303/1303), 810.02 KiB | 251 KiB/s, done.
Resolving deltas: 100% (742/742), done.

$ cd plasm.js

$ npm install
npm http GET https://registry.npmjs.org/f.js
npm http GET https://registry.npmjs.org/simplexn.js
npm http 304 https://registry.npmjs.org/simplexn.js
npm http 304 https://registry.npmjs.org/f.js
f.js@0.5.0 ./node_modules/f.js

simplexn.js@0.1.4 ./node_modules/simplexn.js

**Comment by vittorioc** [comment]
Bene, mi fa piacere che funzioni tutto.

Allora adesso puoi anche chiudere l'issue.
