### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by marcoliceti** [cvdlab/plasm.js#21]
Normal procedure (git clone + submodule init + submodule update) seems no more to be working.

I solved by:
1. Removing node_modules directory from .gitignore
2. Manually adding simplexn.js ed f.js submodules (using node_modules directory)

**Comment by furio** [comment]
The correct procedure have now two prerequisites: git and node being installed.
Then proceed with "git clone" of the plasm.js repository, enter in your local copy and run "npm update" to get the correct dependencies configures.
In the "test/" directory you can use the "index.html" to work with your local copy of plasm.js (suggested browser Chrome/Chromium)

**Comment by marcoliceti** [comment]
Thank you!
