### ISSUE TITLE
T()()(R()()(CIRCLE()())) and S()()(R()()(CIRCLE()())) bug.

### ISSUE THREAD

**Issue by ziofab** [cvdlab/plasm.js#24]
The function CIRCLE()() draws a circle on the XY plane.
If I bring the circle in the YZ plane with a ROTATE()()() and then I make a TRANSLATE()()() then the circle return back in the XY plane

var c = CIRCLE()();
var cr = R([0,2])([PI/2])(c);
var c0 = T([0,1,2])([0,0,0])(cr); // Bug
var cs = S([0,1,2])([1,1,1])(cr); // Bug
DRAW(cr);
DRAW(c0);

The two DRAW() should draw the same circles, but they actually draws two orthogonal circles!
I saw that in this case the SCALE()()() behave like TRANSLATE()()(): DRAW(cs) is the same of DRAW(c0).

The following code seems that works:

var domain = DOMAIN([[0,2*PI]])([32]);
var mapping = function (v) { return [SIN(v[0]), COS(v[0]), 0]; };
var c = MAP(mapping)(domain);
var cr = R([0,2])([PI/2])(c);
var c0 = T([0,1,2])([0,0,0])(cr);
var cs = S([0,1,2])([1,1,1])(cr);
DRAW(c0);

If I delete the third coordinate in the mapping then I experience the same problem of CIRCLE()(): to have the problem then change the mapping function of the working code into "var mapping = function (v) { return [SIN(v[0]), COS(v[0])]; }; ".

I saw that DISK()() behave like CIRCLE()().
So the problem should lie in ROTATE()()(), which makes some mistakes in transforming the two-dimensional object returned by CIRCLE()() to an object in three dimensions.

Thanks

**Comment by federicospini** [comment]
fixed :)
problem was due to implicit embed performed by `rotate`, `scale` and `translate` transformation methods in `simplexn.js`
