### ISSUE TITLE
Errore su export SIMPLEXGRID

### ISSUE THREAD

**Issue by dario1089** [cvdlab/plasm.js#3]
la funzione SIMPLEXGRID prende in input un parametro chiamato quotes ed utilizza un altro parametro non definito all'interno della funzione. Fixato in questo modo funziona:

SIMPLEXGRID = function (quotes) {
    return p.simplexGrid(quotes);
}

**Comment by federicospini** [comment]
Sistemato.

La prossima volta prova tu stesso a fare una pull request :)
