### ISSUE TITLE
Bug - Disk and Struct

### ISSUE THREAD

**Issue by vddp** [cvdlab/plasm.js#32]
//The following code display a model of a disk but an incorrect output if the same disk is inserted into a struct
var disk = DISK(1)([]);
var disk_placed = T([2])([1])(disk);
DRAW(disk_placed);

var disk_Struct = STRUCT ([disk_placed]);
DRAW(disk_Struct);

//Note: the error is supposed to be related with the z-axis translation (in fact the following code works properly)
var disk = DISK(1)([]);
var disk_placed = T([0,1])([1,1])(disk);
DRAW(disk_placed);

var disk_Struct = STRUCT ([disk_placed]);
DRAW(disk_Struct);

**Comment by federicospini** [comment]
fixed :)
problem was due to implicit embed performed by `rotate`, `scale` and `translate` transformation methods in `simplexn.js`
