### ISSUE TITLE
ROTATE

### ISSUE THREAD

**Issue by Newsid** [cvdlab/plasm.js#5]
Ho provato ad utilizzare la funzione ROTATE ma non ha prodotto alcun risultato.

Il codice che ho usato è questo:

var cuboid = CUBOID([1,2,3]);
DRAW(ROTATE([2])(PI/3)(cuboid));

Quel DRAW ha semplicemente rappresentato l'oggetto normale senza nessuna rotazione.

Sto usando male la funzione o c'e' qualcosa che non va?

Grazie!

**Comment by MangakaFan** [comment]
Io l'ho usato in una maniera simile e mi ha funzionato:

var cube = CUBOID([1,2,3]);
var rotatedCube = ROTATE(2)(PI/4)(cube);
DRAW(rotatedCube);

Credo che il problema sia che come primo parametro hai usato [2] invece di 2.
Nella definizione di ROTATE c'è scritto che 'axis' deve essere un numero, ma nell'esempio viene usato un Array.

**Comment by Newsid** [comment]
Ho provato come hai detto te e mi ha dato errore

var rotatedCube = ROTATE([2])(PI/4)(cuboid);
undefined
var rotatedCube = ROTATE(2)(PI/4)(cuboid);
TypeError: Cannot use 'in' operator to search for '0' in 2

Info aggiuntive: sto eseguendo da questo indirizzo: http://cvd-lab.github.com/plasm.js/

**Comment by MangakaFan** [comment]
Anche io ho eseguito da questo indirizzo (usando Chrome 18.0.1025.142)...

**Comment by Newsid** [comment]
io Chrome 18.0.1025.142 per Mac

**Comment by Newsid** [comment]
non ha senso... ora funziona (come dicevi te) -_-
stesso chrome, stesso indirizzo, stesse righe di codice :\

Grazie MangakaFan!

**Comment by federicospini** [comment]
We updated ROTATE and fidex docs according to @MangakaFan explanation :)

Thanks @MangakaFan
