### ISSUE TITLE
Error in SIMPLICIAL_COMPLEX demos

### ISSUE THREAD

**Issue by Rayzen** [cvdlab/plasm.js#6]
La demo d'esempio sulla funzione SIMPLICIAL_COMPLEX da questo errore TypeError: Cannot read property 'position' of undefined

il codice andrebbe corretto così:
var points = [[0,0],[1,0],[0,1],[1,1],[0.5,1.5]];
var cells = [[0,1,2],[1,3,2],[2,3,4]];
var simplicialComplex = SIMPLICIAL_COMPLEX(points)(cells);

**Comment by federicospini** [comment]
Fixed :)

Thanks @Rayzen
