### ISSUE TITLE
Error using CUBE

### ISSUE THREAD

**Issue by MangakaFan** [cvdlab/plasm.js#8]
Ho provato ad utilizzare la funzione CUBE(dim) come nell'esempio proposto:

var dim = 2.5;
var cube = CUBE(dim);
DRAW(cube);

Tuttavia Plasm si blocca (non si possono nemmeno spostare gli assi) e non disegna nulla.

**Comment by furio** [comment]
Credo che ci sia un errore nell'esempio proposto. 
CUBE(d) disegna un d-Cubo unitario quindi se gli dai 2 fa' un quadrato, se gli dai 3 fa' un cubo, 4 ipercubo eccc. Se gli dai 2.5 non vedo che michia possa usci' fuori xD
(a livello di codice fa' un check implicito su 0... se gli dai un numero decimale... loop infinito xD)

**Comment by federicospini** [comment]
@furio perfectly explained what happened!

docs are now updated :)

thanks @furio
